import './globals.css'
import HeaderComponent from '@/components/header'
import FooterComponent from '@/components/footer'
import { Montserrat } from 'next/font/google'
const MontserratFont = Montserrat({ subsets: ['latin'],weight : '400' })

export const metadata = {
  title: 'Khay Khun',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${MontserratFont.className} bg-gradient-to-bl from-white to-gray-200`}>
        <HeaderComponent/>
        <main className=''>
        {children}
        </main>
        <FooterComponent/>
      </body>
    </html>
  )
}
